---
kind: pipeline
type: docker
name: default

steps:
  - name: app-compile
    image: gramoss/mini-build-base:void
    pull: always
    environment:
      MIX_ENV: prod
    commands:
      - xbps-install -Sy git
      - mix deps.get
      - mix compile

  - name: assets-build
    image: node:lts-hydrogen
    commands:
      - npm install --location=global pnpm@8.11.0
      - pnpm --prefix assets install
      - pnpm --prefix assets run deploy

  - name: app-build
    image: gramoss/mini-build-base:void
    environment:
      MIX_ENV: prod
    commands:
      - xbps-install -Sy git
      - mix local.hex --force
      - mix local.rebar --force
      - mix phx.digest
      - mix release

  - name: generate-image-tags
    image: busybox
    when:
      branch:
        - master
      event:
        - push
    commands:
      - echo -n "$(date +'%Y%m%d'),latest" > .tags

  - name: image-push-void-base
    image: plugins/docker
    settings:
      repo: gramoss/policr-mini
      username: gramoss
      password:
        from_secret: gramoss_hub_password
      dockerfile: Dockerfile.amd64ci
      tags: void-base
    when:
      branch:
        - test/void-base
      event:
        - push

  - name: image-push-develop
    image: plugins/docker
    settings:
      repo: telestd/policr-mini
      username: telestd
      password:
        from_secret: hub_pass_telestd
      dockerfile: Dockerfile.amd64ci
      tags: develop
    when:
      branch:
        - develop
      event:
        - push

  - name: image-push-master
    image: plugins/docker
    settings:
      repo: telestd/policr-mini
      username: telestd
      password:
        from_secret: hub_pass_telestd
      dockerfile: Dockerfile.amd64ci
    when:
      branch:
        - master
      event:
        - push
