kind: pipeline
name: default

steps:
  - name: app-compile
    image: bluerain/elixir:1.10.3-slim
    environment:
      MIX_ENV: prod
    commands:
      - mix deps.get
      - mix compile

  - name: assets-build
    image: node:buster
    commands:
      - npm install --prefix assets
      - npm run deploy --prefix assets

  - name: app-build
    image: bluerain/elixir:1.10.3-slim
    pull: always
    environment:
      MIX_ENV: prod
    commands:
      - mix phx.digest
      - mix release

  - name: image-build
    image: docker
    commands:
      - docker build . -t bluerain/policr-mini
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock
