---
kind: pipeline
type: docker
name: default

steps:
  - name: app-compile
    image: elixircn/elixir:1.14.5-otp-26-slim
    environment:
      MIX_ENV: prod
    commands:
      - apt update && apt install git -y
      - mix local.hex --force
      - mix local.rebar --force
      - mix deps.get
      - mix compile

  - name: assets-build
    image: node:lts-hydrogen
    commands:
      - npm install --location=global pnpm@8.6.7
      - pnpm --prefix assets install
      - pnpm --prefix assets run deploy

  - name: app-build
    image: elixircn/elixir:1.14.5-otp-26-slim
    pull: always
    environment:
      MIX_ENV: prod
    commands:
      - apt update && apt install git -y
      - mix local.hex --force
      - mix local.rebar --force
      - mix phx.digest
      - mix release

  - name: image-push-develop
    image: plugins/docker
    settings:
      repo: telestd/policr-mini
      username: telestd
      password:
        from_secret: hub_pass_telestd
      dockerfile: Dockerfile
      tags: develop
    when:
      branch:
        - develop
      event:
        - push

  - name: image-push-master
    image: plugins/docker
    settings:
      repo: telestd/policr-mini
      username: telestd
      password:
        from_secret: hub_pass_telestd
      dockerfile: Dockerfile
      tags: latest
    when:
      branch:
        - master
      event:
        - push
