[tools]
erlang = "28.0.2"
elixir = "1.18.4-otp-28"
"npm:pnpm" = "10"
"cargo:dprint" = "latest"

[tasks.setup]
run = [
  "mise run env-deps up -d --wait",
  "mix deps.get",
  "mise run admin-setup",
  "mise run console-setup",
  "mise run assets-setup",
  "mise run front-setup",
  "mix ecto.setup",
]

[tasks.default]
env = { PHX_SERVER = "true", BOT_SERVER = "true" }
run = "iex -S mix"

[tasks.bot]
env = { BOT_SERVER = "true" }
run = "iex -S mix"

[tasks.web]
env = { PHX_SERVER = "true" }
run = "iex -S mix"

[tasks.format]
depends = ["mix-format", "dprint-fmt"]

[tasks.lint]
depends = ["mix-lint", "admin-lint", "console-lint", "front-lint"]

[tasks.prepare]
depends = ["format", "lint"]

[tasks.test]
run = ["mix test"]

[tasks.clean]
depends = ["mix-clean", "admin-clean", "console-clean", "front-clean", "output-clean"]

[tasks.destory]
depends = ["clean"]
run = "mise run env-deps down -v"

[tasks.env-deps]
run = "docker compose -f docker-compose.dev.yml --env-file dev.env"

[tasks.mix-clean]
run = ["mix clean", "rm -rf deps _build"]

[tasks.mix-check]
depends = ["mix-format", "mix-lint"]

[tasks.mix-format]
run = "mix format"

[tasks.mix-lint]
run = ["mix credo --strict --mute-exit-status", "mix dialyzer"]

[tasks.front-setup]
run = "mise run front-pnpm install"

[tasks.front-lint]
run = "mise run front-pnpm run lint"

[tasks.front-clean]
run = ["rm -rf webapps/node_modules", "rm -rf priv/static/assets"]

[tasks.front-pnpm]
run = "pnpm --prefix webapps"

[tasks.admin-setup]
run = "mise run admin-pnpm install"

[tasks.admin-lint]
run = "mise run admin-pnpm run lint"

[tasks.admin-clean]
run = ["rm -rf admin/node_modules"]

[tasks.admin-pnpm]
run = "pnpm --prefix admin"

[tasks.console-setup]
run = "mise run console-pnpm install"

[tasks.console-lint]
run = "mise run console-pnpm run lint"

[tasks.console-clean]
run = ["rm -rf console/node_modules"]

[tasks.console-pnpm]
run = "pnpm --prefix console"

[tasks.assets-setup]
run = "pnpm install --prefix assets"

[tasks.dprint-fmt]
run = "dprint fmt"

[tasks.bye]
run = "mise run env-deps stop"

[tasks.output-clean]
run = ["rm -rf test/assets/output/*", "rm -rf _assets/_cache/*"]

[tasks.count]
run = "cloc lib test config priv/repo priv/gettext priv/rel benches admin/src admin/types console/src console/types assets/src assets/styles webapps/src webapps/types"
