when:
  - path:
      exclude: ["README.md", ".drone.yml", "justfile", "shell.nix"]

steps:
  app-compile:
    image: gramoss/mini-build-base:void
    pull: true
    environment:
      MIX_ENV: prod
    commands:
      - xbps-install -Sy git
      - mix deps.get
      - mix compile

  app-assets-build:
    image: node:lts-hydrogen
    commands:
      - npm install --location=global pnpm@8.13.0
      - pnpm --prefix assets install
      - pnpm --prefix assets run deploy

  app-release:
    image: gramoss/mini-build-base:void
    environment:
      MIX_ENV: prod
    commands:
      - xbps-install -Sy git
      - mix local.hex --force
      - mix local.rebar --force
      - mix phx.digest
      - mix release

  multiarch-image-build-push:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: gramoss/policr-mini
      username: gramoss
      password:
        from_secret: gramoss_pass
      dockerfile: Dockerfile.multiarch
      platforms: linux/amd64,linux/arm64/v8
      tags:
        - develop
    when:
      branch: develop
      event: push
