steps:
  app-compile:
    image: gramoss/mini-build-base:20240329
    pull: true
    environment:
      MIX_ENV: prod
    commands:
      - xbps-install -Sy git
      - mix deps.get
      - mix compile

  app-assets-build:
    image: node:20
    commands:
      - npm install --location=global pnpm@9.0.5
      - pnpm --prefix assets install
      - pnpm --prefix assets run deploy
      - pnpm --prefix webapps install
      - pnpm --prefix webapps build

  app-release:
    image: gramoss/mini-build-base:20240329
    environment:
      MIX_ENV: prod
    commands:
      - xbps-install -Sy git
      - mix local.hex --force
      - mix local.rebar --force
      - mix phx.digest
      - mix release

  develop-image-build-push:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: gramoss/policr-mini
      username: gramoss
      password:
        from_secret: gramoss_pass
      dockerfile: Dockerfile.amd64ci
      tags:
        - develop
    when:
      branch: develop
      event: push

  generate-image-tags:
    image: busybox
    when:
      branch: master
      event: push
    commands:
      - echo -n "$(date +'%Y%m%d'),latest" > .tags

  multiarch-image-build-push:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: gramoss/policr-mini
      username: gramoss
      password:
        from_secret: gramoss_pass
      dockerfile: Dockerfile.multiarch
      platforms: linux/amd64,linux/arm64/v8
    when:
      branch: master
      event: push

  schedule-pre-deploy:
    image: curlimages/curl
    commands:
      - curl -f -X POST $PRE_DEPLOY_HOOK_URL
    secrets: [PRE_DEPLOY_HOOK_URL]
    when:
      branch: develop
      event: push
