when:
  - branch: [develop]
    event: push

steps:
  app-compile:
    image: gramoss/mini-build-base:20240521
    pull: true
    environment:
      MIX_ENV: prod
    commands:
      - xbps-install -Sy git
      - mix deps.get
      - mix compile

  app-assets-build:
    image: node:20
    commands:
      - npm install --location=global pnpm@10
      - pnpm --prefix assets install
      - pnpm --prefix assets run deploy
      - pnpm --prefix webapps install
      - pnpm --prefix webapps build

  app-release:
    image: gramoss/mini-build-base:20240521
    environment:
      MIX_ENV: prod
    commands:
      - xbps-install -Sy git
      - mix local.hex --force
      - mix local.rebar --force
      - mix phx.digest
      - mix release

  app-image-build-push:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: gramoss/policr-mini
      username: gramoss
      password:
        from_secret: gramoss_pass
      dockerfile: Dockerfile.ci
      platforms: linux/arm64/v8
      tags:
        - arm-develop
    when:
      branch: develop
      event: push
