name: Publish

on:
  push:
    branches: ["main"]
    tags: ["*"]

permissions:
  contents: read

jobs:
  publish-docker:
    name: Publish Docker image
    environment: production
    runs-on: ubuntu-latest
    # needs: build-test
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            gramoss/policr-mini
          tags: |
            type=raw,value=weekly,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
            type=match,pattern=\d{8},group=0,enable=${{ startsWith(github.ref, 'refs/tags/') }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
